### ISSUE TITLE
Commad not added to the `$PATH`

### ISSUE THREAD

**Issue by ivansenic** [paketo-buildpacks/jattach#142]
When building with the base image `paketobuildpacks/builder-jammy-base:latest` and `BP_JATTACH_ENABLED=true`, the `jattach` layer is added, but executable is not added to to path, nor included in any folders included in the path.

```
cnb@plainly-backend-86787d8f85-hbhzk:/$ ./layers/paketo-buildpacks_jattach/jattach/bin/jattach             
jattach 2.2 built on Jan 10 2024

Usage: jattach <pid> <cmd> [args ...]

Commands:
    load  threaddump   dumpheap  setflag    properties
    jcmd  inspectheap  datadump  printflag  agentProperties

cnb@plainly-backend-86787d8f85-hbhzk:/$ jattach
bash: jattach: command not found

cnb@plainly-backend-86787d8f85-hbhzk:/$ echo $PATH
/cnb/process:/cnb/lifecycle:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

## Expected Behavior

Command should be in the path.

## Steps to Reproduce

1. I managed to hit it by using the spring boot gradle-based docker image build, setup as:

```
tasks.named("bootBuildImage") {
    builder = 'paketobuildpacks/builder-jammy-base:latest'
    environment["BP_JATTACH_ENABLED"] = "true"
}

```

**Comment by dmikusa** [comment]
This is mostly likely due to how you're entering the container. The fact that the jattach layer is present, means the launcher will put it on the path, that's guaranteed by the buildpack spec. Problems can occur when you enter a container and bypass the launcher though because it doesn't have a chance to set up the path correctly.

Make sure you're entering the container by invoking the launcher. This happens automatically when your app runs, but you need to specifically invoke the launcher if you're entering a container manually and you want the environment set up.

```
docker run --rm --entrypoint launcher -it multi-process-app bash
```

https://buildpacks.io/docs/for-app-developers/how-to/build-outputs/specify-launch-process/#user-provided-shell-process

If that doesn't work, please let me know.

**Comment by ivansenic** [comment]
Yea I am trying to enter into a running container on k8s. It seems a bit complex, but this does indeed work:

```
kubectl exec -n namespace -it container -- /cnb/lifecycle/launcher /bin/bash
```

**Comment by dmikusa** [comment]
Yes, that's what you want for K8s. Glad it's working. Thanks for following up!
